// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrhSsdvjQ45YuHMLapvKjdoKluC4MXfSE',
    appId: '1:1023860608167:web:ea844ca55e872cde4c9f82',
    messagingSenderId: '1023860608167',
    projectId: 'fire-app-ea2e4',
    authDomain: 'fire-app-ea2e4.firebaseapp.com',
    storageBucket: 'fire-app-ea2e4.appspot.com',
    measurementId: 'G-GW08SST70K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAls2h7S6V9Y8kZbKBI_eWj61qioRoPCJA',
    appId: '1:1023860608167:android:d38a0455625069ba4c9f82',
    messagingSenderId: '1023860608167',
    projectId: 'fire-app-ea2e4',
    storageBucket: 'fire-app-ea2e4.appspot.com',
  );
}
